### ISSUE TITLE
"Add a new Pack pocket" tutorial - Left/right pocket switch bug

### ISSUE THREAD

**Issue by BOOST15673** [pret/pokecrystal#794]
In the normal overworld and in battle, the bag functions as expected:
Items <-> Balls <-> Berries <-> Key Items <-> TM/HM <-> Items.
However, in a Mart's sell menu, party Pokemon's Give item menu, Pokecenter's PC Deposit menu, it is not as expected:
Items <-> Balls <-> Key Items <-> TMs/HMs <-> Berries <-> Items.
The Berries pack shifted from spot 3 to 5. This is by both protagonist genders.

Otherwise, it works flawlessly and I am so very grateful for this and can't thank you people enough!

**Comment by MajorAgnostic** [comment]
You just have to change all of the PACKSTATE_ parts of pack.asm so that they match the correct left/right order. For example, the tutorial says:

```.KeyItemsPocketMenu:
 	...
-	ld b, PACKSTATE_INITBALLSPOCKET ; left
+	ld b, PACKSTATE_INITBERRYPOCKET ; left
 	ld c, PACKSTATE_INITTMHMPOCKET ; right
 	call Pack_InterpretJoypad
 	ret c
 	call .ItemBallsKey_LoadSubmenu
 	ret```
 	
 This makes it so that the Berry pocket is left of the Key Items Pocket (the new 3rd slot), 
 when you actually want the Berry pocket to be left of the Items pocket (in which case it would be 5th). 
 Make sure to change all of them, there's two sets for each pocket menu.

**Comment by Idain** [comment]
I've managed to fix it. Here are the steps I took:

1. In [constants/item_data_constants.asm](https://github.com/pret/pokecrystal/blob/master/constants/item_data_constants.asm), change the order of the pack pockets constants so that BERRY_POCKET ends being the 3rd item on the list:


```
; pack pockets 
const_def
	const ITEM_POCKET       ; 0
	const BALL_POCKET       ; 1
	const BERRY_POCKET      ; 2
	const KEY_ITEM_POCKET   ; 3
	const TM_HM_POCKET      ; 4
```
	
2. In [engine/overworld/select_menu.asm](https://github.com/pret/pokecrystal/blob/master/engine/overworld/select_menu.asm) change the order of the entries in `.Pockets` so that they match with the *_POCKET constants:

```
.Pockets:
; entries correspond to *_POCKET constants
	dw .CheckItem
	dw .CheckBall
	dw .CheckBerry
	dw .CheckKeyItem
	dw .CheckTMHM
```

3. In [engine/items/pack.asm](https://github.com/pret/pokecrystal/blob/master/engine/items/pack.asm), change the order of the PACKSTATE_* constants so that PACKSTATE_INITBERRYPOCKET and PACKSTATE_BERRYPOCKETMENU are placed between the BALLS and KEYITEMS constants:

```
; Pack.Jumptable and BattlePack.Jumptable indexes
	const_def
	const PACKSTATE_INITGFX            ;  0
	const PACKSTATE_INITITEMSPOCKET    ;  1
	const PACKSTATE_ITEMSPOCKETMENU    ;  2
	const PACKSTATE_INITBALLSPOCKET    ;  3
	const PACKSTATE_BALLSPOCKETMENU    ;  4
	const PACKSTATE_INITBERRYPOCKET    ;  5
	const PACKSTATE_BERRYPOCKETMENU	   ;  6
	const PACKSTATE_INITKEYITEMSPOCKET ;  7
	const PACKSTATE_KEYITEMSPOCKETMENU ;  8
	const PACKSTATE_INITTMHMPOCKET     ;  9
	const PACKSTATE_TMHMPOCKETMENU     ;  10
	const PACKSTATE_QUITNOSCRIPT       ;  11
	const PACKSTATE_QUITRUNSCRIPT      ;  12
```
	
Also, we need to change the order of all Jumptables entries whose order corresponds to PACKSTATE_* and *_POCKET constants:

```
Pack:
 	...

 .Jumptable:
 ; entries correspond to PACKSTATE_* constants
	dw .InitGFX            ;  0
	dw .InitItemsPocket    ;  1
	dw .ItemsPocketMenu    ;  2
	dw .InitBallsPocket    ;  3
	dw .BallsPocketMenu    ;  4
	dw .InitBerryPocket    ;  5
	dw .BerryPocketMenu    ;  6
	dw .InitKeyItemsPocket ;  7
	dw .KeyItemsPocketMenu ;  8
	dw .InitTMHMPocket     ;  9
	dw .TMHMPocketMenu     ;  10
	dw Pack_QuitNoScript   ;  11
	dw Pack_QuitRunScript  ;  12
```

```
BattlePack:
 	...

 .Jumptable:
; entries correspond to PACKSTATE_* constants
	dw .InitGFX            	;  0
	dw .InitItemsPocket    	;  1
	dw .ItemsPocketMenu    	;  2
	dw .InitBallsPocket    	;  3
	dw .BallsPocketMenu    	;  4
	dw .InitBerryPocket 	;  5
	dw .BerryPocketMenu 	;  6
	dw .InitKeyItemsPocket 	;  7
	dw .KeyItemsPocketMenu 	;  8
	dw .InitTMHMPocket     	;  9
	dw .TMHMPocketMenu     	;  10
	dw Pack_QuitNoScript   	;  11
	dw Pack_QuitRunScript  	;  12
```

```
DepositSellPack:
 	...

 .Jumptable:
 ; entries correspond to *_POCKET constants
 	dw .ItemsPocket
 	dw .BallsPocket
        dw .BerryPocket
 	dw .KeyItemsPocket
 	dw .TMHMPocket
```

 ```
TutorialPack:
 	...

 .dw
 ; entries correspond to *_POCKET constants
 	dw .Items
 	dw .Balls
         dw .Berries
 	dw .KeyItems
 	dw .TMHM
```

4. The following steps are more graphical-related. Change the order of the PackGFXPointers so that the Berry pocket is the 3rd item on the list:

```
PackGFXPointers:
	dw PackGFX + (15 tiles) * 1 ; ITEM_POCKET
        dw PackGFX + (15 tiles) * 3 ; BALL_POCKET
	dw PackGFX + (15 tiles) * 4 ; BERRY_POCKET
	dw PackGFX + (15 tiles) * 0 ; KEY_ITEM_POCKET
	dw PackGFX + (15 tiles) * 2 ; TM_HM_POCKET
```
   	
**NOTE:** Remember to also apply this change to the Crystal-only female pack in [pack_kris.asm](https://github.com/pret/pokecrystal/blob/master/engine/items/pack_kris.asm).

5. Finally, edit [pack_menu.tilemap](https://github.com/pret/pokecrystal/blob/master/gfx/pack/pack_menu.tilemap) and change the order of the label boxes so that Berry is the 3rd item. I recommend using Tilemap Studio for that.

And that's it! I tested this by placing items in all the pockets and opening/closing them in the overworld, during battle, while depositing/withdrawing items in the PC and selling items in the PokéMart.

**Comment by Idain** [comment]
The tutorial has been updated and an extra step has been added to show how to create/edit [pack_menu.tilemap](.../blob/master/gfx/pack/pack_menu.tilemap).

**Comment by coltongit** [comment]
Can this issue be closed since the underlying bug has been resolved by your edits, @Idain? Thanks again!

**Comment by Idain** [comment]
Unfortunately, Rangi reverted my change some months ago without apparent reason, so the problem is still there

**Comment by coltongit** [comment]
Perhaps there was some reason she did that. @Rangi42 was there some specific reason you undid the bugfix that was made for this particular bug?Sent from my Galaxy
-------- Original message --------From: Idain ***@***.***> Date: 2021-09-06  5:10 p.m.  (GMT-04:00) To: pret/pokecrystal ***@***.***> Cc: "Colton G. Rushton" ***@***.***>, Comment ***@***.***> Subject: Re: [pret/pokecrystal] "Add a new Pack pocket" tutorial - Left/right
  pocket switch bug (#794) 
Unfortunately, Rangi reverted my change some months ago without apparent reason, so the problem is still there

**Comment by coltongit** [comment]
@Idain seems like the fix hasn't been changed, now that I'm looking at the wiki page further, it was just moved back to the 5th slot of the bag rather than the 3rd.

**Comment by coltongit** [comment]
Would it make more sense just to convert the tutorial so it uses the entire 5th slot of the bag instead of the 3rd without causing the actual issue it spawned? At least then it still fixes the inconsistency that caused this issue to begin with

**Comment by coltongit** [comment]
Wondering if the whole tutorial now works correctly with `Berries` at slot 5 of the bag. @BOOST15673 Does the tutorial as it is now satisfy what you were looking for from this issue?

**Comment by Idain** [comment]
> Would it make more sense just to convert the tutorial so it uses the entire 5th slot of the bag instead of the 3rd without causing the actual issue it spawned? At least then it still fixes the inconsistency that caused this issue to begin with

The place doesn't matter. The objective is to implement a new pack pocket, after all.

**Comment by coltongit** [comment]
> > Would it make more sense just to convert the tutorial so it uses the entire 5th slot of the bag instead of the 3rd without causing the actual issue it spawned? At least then it still fixes the inconsistency that caused this issue to begin with
> 
> The place doesn't matter. The objective is to implement a new pack pocket, after all.

If the bag placement is at least consistent across all uses of the bag, we can safely say this issue is solved

**Comment by coltongit** [comment]
The bag placement appears to be consistent now across the tutorial
@BOOST15673 Can you confirm please with these changes as they are now?

**Comment by vulcandth** [comment]
Using Rangi's "Fix Labels" commit from Dec 23, 2020.. This issue may be resolved by applying the following changes:

```diff
 DepositSellPack:
 .loop
     call .RunJumptable
     call DepositSellTutorial_InterpretJoypad
     jr c, .loop
     ret
 
 .RunJumptable:
     ld a, [wJumptableIndex]
     ld hl, .Jumptable
     call Pack_GetJumptablePointer
     jp hl
 
 .Jumptable:
 ; entries correspond to *_POCKET constants
     dw .ItemsPocket
     dw .BallsPocket
+    dw .BerryPocket
     dw .KeyItemsPocket
     dw .TMHMPocket
-    dw .BerryPocket
```
Seems like `DepositSellPack` doesn't have hardcoded LEFT/RIGHT entries, so it seems fine to re-arrange the jumptable order so that the LEFT/RIGHT bag navigation matches the Overworld.



`GetPocketCapacity:`
```diff
 .not_pc
    ld c, MAX_BERRIES
    ld a, e
-   cp LOW(wBerries)
+   cp LOW(wNumBerries)
    jr nz, .not_berries
    ld a, d
    cp HIGH(wNumBerries)
    ret z

.not_berries
     ld c, MAX_BALLS
     ret
```
This has been tested to verify that the Bag navigation works as expected in the overworld, Mart, Mon Giveitem menu, and PC deposit menu, and battles. 
Items <-> Balls <-> Berries <-> Key Items <-> TM/HM <-> Items.
Tutorial wiki page has been updated.

**Comment by vulcandth** [comment]
I believe this issue to be resolved. If anyone still has a problem with the wiki page now with these latest changes; feel free to contact me.
